apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: daad
  name: daad
  labels:
    app: daad
spec:
  selector:
    matchLabels:
      app: daad
  template:
    metadata:
      labels:
        app: daad
        name: daad
    spec:
      containers:
        - name: daad
          image: mahendraintelops/dsada/daad
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 3233
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        